#!/bin/sh
if [ "$*" = "-rn" ]; then
  echo "Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            2.2.3.1            UGSc           60        0     en0
127                127.0.0.1          UCS             1        0     lo0
127.0.0.1          127.0.0.1          UH             24 34170957     lo0
169.254            link#4             UCS             1        0     en0
192.168.1          link#4             UCS            11        0     en0
192.168.1.1/32     link#4             UCS             2        0     en0
192.168.1.1        22:22:22:22:22:22  UHLWIir        61      388     en0   1154

Internet6:
Destination                             Gateway                         Flags         Netif Expire
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en0/64                           link#4                          UCI             en0
ff02::%awdl0/32                         link#10                         UmCI          awdl0"
fi
