#!/bin/bash

if [ "$*" = "addr show" ]; then
echo "1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 01:01:01:00:00:01 brd ff:ff:ff:ff:ff:ff
    inet 1.2.3.5/24 brd 1.2.3.0 scope global eth0
    inet6 2600:a000:0:1000::20:0001/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::600:010f:f000:0001/64 scope link
       valid_lft forever preferred_lft forever"
fi

if [ "$*" = "route" ]; then
echo "1.2.3.0/24 dev eth0  proto kernel  scope link  src 1.2.3.4
169.254.0.0/16 dev eth0  scope link  metric 1002
default via 1.2.3.1 dev eth0
"
fi
